# Generated by Django 4.1.7 on 2023-06-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_clientprofilemodel_delete_clientmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofilemodel',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
