# Generated by Django 4.1.7 on 2023-06-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_accesstoken_accesstokenmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesstokenmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='accesstokenmodel',
            name='token',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
