# Generated by Django 4.1.7 on 2023-06-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_accesstokenmodel_delete_tokenmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofilemodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
