# Generated by Django 4.1.7 on 2023-06-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_clientprofilemodel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofilemodel',
            name='email',
        ),
    ]
