# Generated by Django 4.1.7 on 2023-06-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailbox', '0004_emailboxmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailModel',
        ),
    ]
