# Generated by Django 4.1.7 on 2023-06-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailbox', '0005_delete_emailmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('emailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailbox.emailboxmodel')),
            ],
        ),
    ]
