# Generated by Django 4.1.7 on 2023-08-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailbox', '0007_emailmodel_total_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='account',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='disposable_provider',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='disposable_status',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='dns_status',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='domain',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='free_status',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='is_valid',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='role',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='role_status',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='emailmodel',
            name='syntax_error_status',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='InstantReplyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emailbox.emailmodel')),
            ],
        ),
    ]
