# Generated by Django 4.1.7 on 2023-06-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_projectmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='product',
            field=models.CharField(choices=[('EMAILBOX', 'EMAILBOX')], max_length=20),
        ),
    ]
